# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160805_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
