# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_product_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.TextField(default=20160725),
            preserve_default=False,
        ),
    ]
