# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20160807_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(default=20160725, max_length=200),
            preserve_default=False,
        ),
    ]
