# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_itemtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtags',
            name='sort_num',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
