# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_itemtags_sort_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='d_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='g_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='o_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemtags',
            name='sort_num',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_hit',
            field=models.IntegerField(default=0),
        ),
    ]
