# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_remove_board_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='text',
            field=models.TextField(default=20160725),
            preserve_default=False,
        ),
    ]
