# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_board_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
