# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
