# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20160807_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
