# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='published_date',
        ),
    ]
